# rbenvのインストール
---
- name: install rbenv
  become: yes
  git: 
    repo: https://github.com/sstephenson/rbenv.git 
    dest: ~/.rbenv


- name: Add rbenv to PATH
  lineinfile: 
    path: ~/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'


- name: eval rbenv init
  lineinfile: 
    path: ~/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Load rbenv setting
  become_user: ec2-user
  shell: bash -lc "source ~/.bash_profile"

#ruby-buildのインストール
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

#rubyのインストール　