---
- name: Change user permission
  become: yes
  ansible.builtin.file:
    path: /home/ec2-user
    state: directory
    mode: 0755

#.envfileの作成
- name: Set.env file
  block: 
  - name: Touch master.key
    file:
      path: /home/ec2-user/raisetech-live8-sample-app/.env
      state: touch

#データベース設定のファイルをコピー  
- name: edit database.yml
  template: 
    src: templates/database.yml
    dest: /home/ec2-user/raisetech-live8-sample-app/config/database.yml
    owner: ec2-user
    group: ec2-user

#.envfileの作成
- name: Set.env
  block: 
  - name: Touch master.key
    file:
      path: /home/ec2-user/raisetech-live8-sample-app/.env
      state: touch

#データベースへのアクセス設定　
- name: Set DB env
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export {{ item }}'
  with_items:
      - "{{ DATABASE_USERNAME }}"
      - "{{ DATABASE_PASSWORD }}"
      - "{{ DATABASE_HOSTNAME }}"

- name: Load database env setting
  become_user: ec2-user
  shell: bash -lc "source ~/.bash_profile"

#.envにRAILS_MASTER_KEY追加 
- name: line in RAILS_MASTER_KEY
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/raisetech-live8-sample-app/.env
    line: RAILS_MASTER_KEY = '{{ master_key }}'

#マスターキーの状態確認 
- name: Check masterkey exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/master.key
  register: masterkey_stat

#マスターキーの作成 
- name: edit credentialfile
  template: 
    src: templates/production.yml.enc.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/credentials.yml.enc
    owner: ec2-user
    group: ec2-user
  when: not masterkey_stat.stat.exists

- name: edit key
  template:
    src: templates/production.key.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/master.key
    owner: ec2-user
    group: ec2-user
  when: not masterkey_stat.stat.exists

- name: edit masterkey
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/raisetech-live8-sample-app/config/master.key
    line: "{{ master_key }}"

#webpackerのビルド  
- name: Build webpacker setting
  become_user: ec2-user
  npm:
    name: build
    path: /home/ec2-user/raisetech-live8-sample-app
#production.rb内のcashe_classをfalseに変更
- name: Cache class change
  ansible.builtin.replace:
    path: /home/ec2-user/raisetech-live8-sample-app/config/environments/production.rb
    regexp: '\bconfig.cache_classes = true\b'
    replace: 'config.cache_classes = false'
#storageの変更
- name: storage change
  ansible.builtin.replace:
    path: /home/ec2-user/raisetech-live8-sample-app/config/environments/production.rb
    regexp: '\bconfig.active_storage.service = :amazon\b'
    replace: 'config.active_storage.service = :local'

#データベースの作成、マイグレーションの実施
- name: Setting database
  become_user: ec2-user
  block:
  - name: Create database
    ansible.builtin.command:
      cmd: bash -lc "bundle exec rails db:create RAILS_ENV=production"
      chdir: /home/ec2-user/raisetech-live8-sample-app/
    ignore_errors: yes
  - name: Migrate database
    ansible.builtin.command:
      cmd: bash -lc "bundle exec rails db:migrate RAILS_ENV=production"
      chdir: /home/ec2-user/raisetech-live8-sample-app/
    ignore_errors: yes

#コンパイルの実施  
- name: asset precompile
  become_user: ec2-user
  ansible.builtin.command:
    cmd: bash -lc "bundle exec rails assets:precompile RAILS_ENV=production"
    chdir: /home/ec2-user/raisetech-live8-sample-app/