---
#Nginxのインストール確認
- name: Check nginx installed
  become: yes
  yum:
    name: nginx
    state: present
  register: check_nginx_installed
  ignore_errors: yes

#Nginxのインストール
- name: Install nginx
  become: yes 
  shell: amazon-linux-extras install -y nginx1
  when: check_nginx_installed is failed

#Nginxの権限を0755へ変更
- name: Change nginx/conf.d ownership
  become: yes
  file:
    path: /etc/nginx/nginx.conf.d
    owner: ec2-user
    group: ec2-user
    mode: '0755'

#Nginxの設定ファイル読み込み
- name: Setting Nginx
  template:
    src: roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
    owner: ec2-user
    group: ec2-user