---
- hosts: TargetNode
  become: yes
  vars_files: vars.yml
  roles:
    - { role: git, tags: git }
    - { role: package, tags: package }
    - { role: ruby, tags: ruby }
    - { role: mysql, tags: mysql }
    - { role: appclone, tags: appclone }