---
#MySQLを一時停止（bundleインストールが処理能力不足でエラーとなる為）
- name: stop mysql
  become: yes
  shell: bash -lc "service mysqld stop"

#gemのアップデート
- name: gem update
  become_user: ec2-user
  shell: bash -lc "gem update --system"  

#bundler　install
- name: install bundler 
  become_user: ec2-user
  shell: bash -lc "gem install bundler"

#gem  install
- name: gem install
  become_user: ec2-user
  ansible.builtin.command:
    cmd: bash -lc "bundle install"
    chdir: /home/ec2-user/raisetech-live8-sample-app/

#停止していたMySQLを起動
- name: stop mysql
  become: yes
  shell: bash -lc "service mysqld start"